language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - RUSTFLAGS="-A unknown-lints -D warnings"

script:
  - cargo build
  - cargo test
  - 'if [[ "${TRAVIS_RUST_VERSION}" = "nightly" ]]; then cargo install --force clippy; cargo clippy; fi'

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
